export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';

export const CATEGORY_ADD_REQUEST = 'CATEGORY_ADD_REQUEST';
export const CATEGORY_ADD_REQUEST_SUCCESS = 'CATEGORY_ADD_REQUEST_SUCCESS';
export const CATEGORY_ADD_REQUEST_FAILURE = 'CATEGORY_ADD_REQUEST_FAILURE';

export const CATEGORY_FETCH_REQUEST = 'CATEGORY_FETCH_REQUEST';
export const CATEGORY_FETCH_REQUEST_SUCCESS = 'CATEGORY_FETCH_REQUEST_SUCCESS';
export const CATEGORY_FETCH_REQUEST_FAILURE = 'CATEGORY_FETCH_REQUEST_FAILURE';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_REQUEST_SUCCESS = 'CATEGORY_UPDATE_REQUEST_SUCCESS';
export const CATEGORY_UPDATE_REQUEST_FAILURE = 'CATEGORY_UPDATE_REQUEST_FAILURE';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_REQUEST_SUCCESS = 'CATEGORY_DELETE_REQUEST_SUCCESS';
export const CATEGORY_DELETE_REQUEST_FAILURE = 'CATEGORY_DELETE_REQUEST_FAILURE';