export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';

export const SINGLE_CATEGORY_ADD_REQUEST = 'SINGLE_CATEGORY_ADD_REQUEST';
export const SINGLE_CATEGORY_ADD_REQUEST_SUCCESS = 'SINGLE_CATEGORY_ADD_REQUEST_SUCCESS';
export const SINGLE_CATEGORY_ADD_REQUEST_FAILURE = 'SINGLE_CATEGORY_ADD_REQUEST_FAILURE';

export const CATEGORY_FETCH_REQUEST = 'CATEGORY_FETCH_REQUEST';
export const CATEGORY_FETCH_REQUEST_SUCCESS = 'CATEGORY_FETCH_REQUEST_SUCCESS';
export const CATEGORY_FETCH_REQUEST_FAILURE = 'CATEGORY_FETCH_REQUEST_FAILURE';

export const SINGLE_CATEGORY_FETCH_REQUEST = 'SINGLE_CATEGORY_FETCH_REQUEST';
export const SINGLE_CATEGORY_FETCH_REQUEST_SUCCESS = 'SINGLE_CATEGORY_FETCH_REQUEST_SUCCESS';
export const SINGLE_CATEGORY_FETCH_REQUEST_FAILURE = 'SINGLE_CATEGORY_FETCH_REQUEST_FAILURE';

export const SINGLE_CATEGORY_UPDATE_REQUEST = 'SINGLE_CATEGORY_UPDATE_REQUEST';
export const SINGLE_CATEGORY_UPDATE_REQUEST_SUCCESS = 'SINGLE_CATEGORY_UPDATE_REQUEST_SUCCESS';
export const SINGLE_CATEGORY_UPDATE_REQUEST_FAILURE = 'SINGLE_CATEGORY_UPDATE_REQUEST_FAILURE';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_REQUEST_SUCCESS = 'CATEGORY_DELETE_REQUEST_SUCCESS';
export const CATEGORY_DELETE_REQUEST_FAILURE = 'CATEGORY_DELETE_REQUEST_FAILURE';

export const SINGLE_CATEGORY_CLEAN_REQUEST = 'SINGLE_CATEGORY_CLEAN_REQUEST';
export const CATEGORY_CLEAN_REQUEST = 'CATEGORY_CLEAN_REQUEST';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_REQUEST_SUCCESS = 'USER_FETCH_REQUEST_SUCCESS';
export const USER_FETCH_REQUEST_FAILURE = 'USER_FETCH_REQUEST_FAILURE';

export const SINGLE_USER_FETCH_REQUEST = 'SINGLE_USER_FETCH_REQUEST';
export const SINGLE_USER_FETCH_REQUEST_SUCCESS = 'SINGLE_USER_FETCH_REQUEST_SUCCESS';
export const SINGLE_USER_FETCH_REQUEST_FAILURE = 'SINGLE_USER_FETCH_REQUEST_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_REQUEST_SUCCESS = 'USER_UPDATE_REQUEST_SUCCESS';
export const USER_UPDATE_REQUEST_FAILURE = 'USER_UPDATE_REQUEST_FAILURE';

export const PENDING_REQUEST = 'PENDING_REQUEST';
export const PENDING_REQUEST_SUCCESS = 'PENDING_REQUEST_SUCCESS';
export const PENDING_REQUEST_FAILURE = 'PENDING_REQUEST_FAILURE';

export const APPROVE_REQUEST = 'APPROVE_REQUEST';
export const APPROVE_REQUEST_SUCCESS = 'APPROVE_REQUEST_SUCCESS';
export const APPROVE_REQUEST_FAILURE = 'APPROVE_REQUEST_FAILURE';

export const REJECT_REQUEST = 'REJECT_REQUEST';
export const REJECT_REQUEST_SUCCESS = 'REJECT_REQUEST_SUCCESS';
export const REJECT_REQUEST_FAILURE = 'REJECT_REQUEST_FAILURE';